name: Run Cluster Test

on:
  push:
    branches: [ main ]

jobs:
  start:
    name: cluster run
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15' # The Go version to download (if necessary) and use.

      - name: Install deps
        run: ./bin/deps

      - name: Create Cluster
        run: ./bin/setup

      - name: Validate Cluster
        run: ./bin/test
